### ISSUE TITLE
Plugin kann nicht installiert werden

### ISSUE THREAD

**Issue by Cleanerrr** [contao-bootstrap/tab#11]
Contao 4.12.3
PHP 7.4
Composer aktualisiert
Alle andere Pakete aktualisiert

Fehler:

`$ /bin/php74 -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /www/htdocs/mywebsite/web/contao-manager.phar.php composer install --prefer-dist --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 8 installs, 5 updates, 2 removals
  - Downloading netzmacht/html (2.0.2)
  - Downloading beberlei/assert (v2.9.9)
  - Downloading spomky-labs/otphp (v9.1.4)
  - Downloading php-http/httplug (v1.1.0)
  - Downloading ralouphie/getallheaders (3.0.3)
  - Downloading guzzlehttp/psr7 (1.8.3)
  - Downloading guzzlehttp/promises (1.5.1)
  - Downloading guzzlehttp/guzzle (6.5.5)
  - Downloading php-http/guzzle6-adapter (v1.1.1)
  - Downloading php-http/client-common (1.11.0)
  - Downloading contao-community-alliance/meta-palettes (2.0.4)
  - Downloading contao-bootstrap/core (2.0.4)
  - Downloading contao-bootstrap/tab (2.0.0)
  - Removing thecodingmachine/safe (v1.3.3)
  - Removing psr/http-client (1.0.1)
  - Installing netzmacht/html (2.0.2): Extracting archive
  - Downgrading beberlei/assert (v3.3.1 => v2.9.9): Extracting archive
  - Downgrading spomky-labs/otphp (v10.0.1 => v9.1.4): Extracting archive
  - Downgrading php-http/httplug (2.2.0 => v1.1.0): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing guzzlehttp/psr7 (1.8.3): Extracting archive
  - Installing guzzlehttp/promises (1.5.1): Extracting archive
  - Installing guzzlehttp/guzzle (6.5.5): Extracting archive
  - Installing php-http/guzzle6-adapter (v1.1.1): Extracting archive
  - Downgrading php-http/client-common (2.5.0 => 1.11.0): Extracting archive
  - Upgrading contao-community-alliance/meta-palettes (2.0.1 => 2.0.4): Extracting archive
  - Installing contao-bootstrap/core (2.0.4): Extracting archive
  - Installing contao-bootstrap/tab (2.0.0): Extracting archive
Package menatwork/contao-multicolumnwizard is abandoned, you should avoid using it. Use menatwork/contao-multicolumnwizard-bundle instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
97 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php vendor/bin/contao-setup
Fatal error: Uncaught Error: Class 'Symfony\Component\EventDispatcher\Event' not found in /www/htdocs/mywebsite/vendor/contao-bootstrap/core/src/Message/Command/InitializeEnvironment.php:26
Stack trace:
#0 /www/htdocs/mywebsite/vendor/composer/ClassLoader.php(571): include()
#1 /www/htdocs/mywebsite/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/www/htdocs/w01...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('ContaoBootstrap...')
#3 /www/htdocs/mywebsite/vendor/contao-bootstrap/core/src/Listener/ConfigSubscriber.php(66): spl_autoload_call('ContaoBootstrap...')
#4 /www/htdocs/mywebsite/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(232): ContaoBootstrap\Core\Listener\ConfigSubscriber::getSubscribedEvents()
#5 /www/htdocs/mywebsite/vendor in /www/htdocs/mywebsite/vendor/contao-bootstrap/core/src/Message/Command/InitializeEnvironment.php on line 26
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\EventDispatcher\Event' not found in /www/htdocs/mywebsite/vendor/contao-bootstrap/core/src/Message/Command/InitializeEnvironment.php:26
Stack trace:
#0 /www/htdocs/mywebsite/vendor/composer/ClassLoader.php(571): include()
#1 /www/htdocs/mywebsite/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/www/htdocs/w01...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('ContaoBootstrap...')
#3 /www/htdocs/mywebsite/vendor/contao-bootstrap/core/src/Listener/ConfigSubscriber.php(66): spl_autoload_call('ContaoBootstrap...')
#4 /www/htdocs/mywebsite/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(232): ContaoBootstrap\Core\Listener\ConfigSubscriber::getSubscribedEvents()
#5 /www/htdocs/mywebsite/vendor in /www/htdocs/mywebsite/vendor/contao-bootstrap/core/src/Message/Command/InitializeEnvironment.php on line 26
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255
# Process terminated with exit code 255
# Result: Unknown error`

**Comment by dmolineus** [comment]
Es muss mindestens `contao-bootstrap/core ^2.0.5` installiert werden, was seit einem Jahr existiert. Davor fehlten entsprechende Abhängigkeiten.
