### ISSUE TITLE
Select Box display failure

### ISSUE THREAD

**Issue by Munsio** [contao-bootstrap/tab#4]
Contao: 3.4.3
Tab: dev-master (df4167f1)

If i duplicate a row with the + icon the select box style disappears

![image](https://cloud.githubusercontent.com/assets/646513/6127376/62b2edae-b12a-11e4-9450-109de3335f97.png)

But the select box is still useable if i click on the empty places

**Comment by dmolineus** [comment]
New Contao release, and the old issue with styled select and the MCW appears again... https://github.com/menatwork/MultiColumnWizard/issues/147

Does it work if you set `chosen => true` to the select? If this solves the issue I would add it to every select which is a child of the mcw.

**Comment by Munsio** [comment]
jep `chosen => true` fix this problem

**Comment by dmolineus** [comment]
The chosen attribute is set where to every select widget in the mcw now.
