### ISSUE TITLE
List View Trennelment Bezeichnung

### ISSUE THREAD

**Issue by baumannsven** [contao-bootstrap/tab#5]
Bei dem Element Reiter Start werden ja die Bezeichnungen der Tabs versehen.
Wäre es möglich den Trennelementen im List View von den Content Element die Bezeichnung der Tabs mit auszugeben?

**Comment by dmolineus** [comment]
Die zukünftige Version v2 für BS 4 wird eine einheitliche Darstellung der Ansichten Trennelemente liefern. Diese beinhaltet auch die Bezeichnung.

**Comment by dmolineus** [comment]
Ist nun in v2 inklusive
