### ISSUE TITLE
Installationsfehlermeldung

### ISSUE THREAD

**Issue by chriza** [contao-bootstrap/tab#8]
Contao Manager 1.2.1
Frische Contao 4.8.5 Installation (keine weiteren Extensions)
Installation contao-bootstrap/bundle

Hallo,
folgende Fehlermeldung hat sich gerade bei der Installation von bootstrap ergeben:

Using version ^2.1 for contao-bootstrap/bundle
/www/htdocs/xxx/xxx/xxx/xxx/contao48development/composer.json has been updated

# Process terminated with exit code 0
# Result: OK

> Resolving dependencies using Composer Cloud v2.1.1

[6.7MiB/0.34s] Loading composer repositories with package information
[7.2MiB/0.42s] Updating dependencies
[1886.1MiB/36.68s] Your requirements could not be resolved to an installable set of packages.
[1886.1MiB/36.69s] 
  Problem 1
    - Conclusion: don't install contao-bootstrap/tab 2.0.4
    - Conclusion: don't install contao-bootstrap/bundle 2.1.1
    - Installation request for symfony/templating (locked at v5.0.1) -> satisfiable by symfony/templating[v5.0.1].
    - Installation request for contao-bootstrap/bundle ^2.1 -> satisfiable by contao-bootstrap/bundle[2.1.0, 2.1.1].
    - Conclusion: don't install beberlei/assert v3.2.6
    - contao-bootstrap/bundle 2.1.0 requires contao-bootstrap/tab ~2.0 -> satisfiable by contao-bootstrap/tab[2.0.0, 2.0.3, 2.0.4].
    - contao-bootstrap/tab 2.0.0 requires beberlei/assert ^2.9 -> satisfiable by beberlei/assert[v2.9.1, v2.9.2, v2.9.3, v2.9.4, v2.9.5, v2.9.6, v2.9.9].
    - contao-bootstrap/tab 2.0.3 requires beberlei/assert ^2.9 -> satisfiable by beberlei/assert[v2.9.1, v2.9.2, v2.9.3, v2.9.4, v2.9.5, v2.9.6, v2.9.9].
    - Can only install one of: beberlei/assert[v2.9.1, v3.2.6].
    - Can only install one of: beberlei/assert[v2.9.2, v3.2.6].
    - Can only install one of: beberlei/assert[v2.9.3, v3.2.6].
    - Can only install one of: beberlei/assert[v2.9.4, v3.2.6].
    - Can only install one of: beberlei/assert[v2.9.5, v3.2.6].
    - Can only install one of: beberlei/assert[v2.9.6, v3.2.6].
    - Can only install one of: beberlei/assert[v2.9.9, v3.2.6].
    - Installation request for beberlei/assert (locked at v3.2.6) -> satisfiable by beberlei/assert[v3.2.6].

**Comment by dmolineus** [comment]
Right now, you need du update all packages when installing `contao-bootstrap/tab`. I'll let this ticket open as enhancement to support `beberlei/assert:^3.0` as well.

**Comment by chriza** [comment]
Hallo,

ich hatte contao-bootstrap/bundle installieren wollen. Siehe meinen Fehlerbericht.

**Comment by dmolineus** [comment]
Ja, und es scheitert an `contao-bootstrap/tab` siehe dem Fehlerbericht. Die von mir beschriebene Lösung bleibt die gleiche.

1. Alle Pakete zum aktualisieren auswählen
2. `contao-bootstrap/bundle` installieren
3. Änderungen anwenden

**Comment by chriza** [comment]
Hallo,
da verstehe ich wohl etwas nicht.
Ich habe eine neu aufgesetzte, leere Contao 4.8.5 Installation und möchte in diese als erste Extension contao-bootstrap/bundle installieren. Dabei wird o.g. Fehler geworfen.

**Comment by chriza** [comment]
Hallo,

ich habe gerade einen weiteren Installationsversuch mit u.a. bootstrap Elementen vorgenommen.
Folgende Fehlermeldung:

$ /usr/bin/php72 -q -d memory_limit=-1 /www/htdocs/xxx/xxx/contao48/web/contao-manager.phar.php composer require contao-bootstrap/core contao-bootstrap/grid contao-bootstrap/form contao-bootstrap/layout contao-bootstrap/templates contao-bootstrap/panel contao-bootstrap/navbar --no-suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Using version ^2.0 for contao-bootstrap/core
Using version ^2.1 for contao-bootstrap/grid
Using version ^2.1 for contao-bootstrap/form
Using version ^2.0 for contao-bootstrap/layout
Using version ^2.1 for contao-bootstrap/templates
Using version ^2.1 for contao-bootstrap/panel
Using version ^2.1 for contao-bootstrap/navbar
/www/htdocs/w0145fb8/webpages/contao48/composer.json has been updated

# Process terminated with exit code 0
# Result: OK


> Resolving dependencies using Composer Cloud v2.1.1

[6.7MiB/0.26s] Loading composer repositories with package information
[7.2MiB/0.34s] Updating dependencies
[1885.7MiB/53.03s] Your requirements could not be resolved to an installable set of packages.
[1885.7MiB/53.05s] 
  Problem 1
    - Conclusion: don't install contao-bootstrap/panel 2.1.1
    - Installation request for contao-bootstrap/panel ^2.1 -> satisfiable by contao-bootstrap/panel[2.1.0, 2.1.1].
    - Conclusion: don't install symfony/templating v5.0.1
    - contao-bootstrap/panel 2.1.0 requires symfony/templating ^3.3 || ^4.0 -> satisfiable by symfony/templating[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1].
    - Can only install one of: symfony/templating[v3.3.0, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.1, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.10, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.11, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.12, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.13, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.14, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.15, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.16, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.17, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.18, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.2, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.3, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.4, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.5, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.6, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.7, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.8, v5.0.1].
    - Can only install one of: symfony/templating[v3.3.9, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.0, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.1, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.10, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.11, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.12, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.13, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.14, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.15, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.16, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.17, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.18, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.19, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.2, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.20, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.21, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.22, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.23, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.24, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.25, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.26, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.27, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.28, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.29, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.3, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.30, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.31, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.32, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.33, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.34, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.35, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.36, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.4, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.5, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.6, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.7, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.8, v5.0.1].
    - Can only install one of: symfony/templating[v3.4.9, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.0, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.1, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.10, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.11, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.12, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.13, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.14, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.15, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.2, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.3, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.4, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.5, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.6, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.7, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.8, v5.0.1].
    - Can only install one of: symfony/templating[v4.0.9, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.0, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.1, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.10, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.11, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.12, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.2, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.3, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.4, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.5, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.6, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.7, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.8, v5.0.1].
    - Can only install one of: symfony/templating[v4.1.9, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.0, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.1, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.10, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.11, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.12, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.2, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.3, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.4, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.5, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.6, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.7, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.8, v5.0.1].
    - Can only install one of: symfony/templating[v4.2.9, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.0, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.1, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.2, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.3, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.4, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.5, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.6, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.7, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.8, v5.0.1].
    - Can only install one of: symfony/templating[v4.3.9, v5.0.1].
    - Can only install one of: symfony/templating[v4.4.0, v5.0.1].
    - Can only install one of: symfony/templating[v4.4.1, v5.0.1].
    - Installation request for symfony/templating (locked at v5.0.1) -> satisfiable by symfony/templating[v5.0.1].

[1885.7MiB/53.08s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[401.6MiB/57.30s] Memory usage: 401.61MB (peak: 1889.44MB), time: 57.3s.
[401.6MiB/57.31s] Finished Composer Cloud resolving.


# Cloud Job ID yVrr46aIlcMJ0bQ4obByxn2J97GdSsH8uGn6azRPdmlJtxfp5hMj3oKvoBFfvawaSbLzSWodVBwtO0bHLEkllOuaq5GRUTOTownsjVWXCG failed

---

### Der Hintergrundprozess wurde unerwartet beendet ###

**Comment by dmolineus** [comment]
Bitte für Supportanfragen das Forum nutzen. Ich habe selbst problemlos `contao-bootstrap/bundle` unter Contao 4.8 am laufen und oben auch schon beschrieben wie es funktioniert. Auch ein leeres Contao beinhaltet Abhängigkeiten, die ggf. neu geprüft werden müssen beim Installieren zusätzlicher Erweiterungen

**Comment by chriza** [comment]
Hallo,
in allen meiner Contao-Installationen habe ich contao-bootstrap/bundle installiert. Ein Update dieser Installationen mit dem Contao-Manager ist problemlos möglich.
Bei einer neuen Contao-Installation sind jetzt die Fehler aufgetreten, sowohl bei ALL-INKL als auch bei IONOS. Die beiden Extensions contao-bootstrap/grid und contao-bootstrap/tab können wegen der beschriebenen Abhängigkeitsfehlern nicht installiert werden.

**Comment by dmolineus** [comment]
Wurde denn die Reihenfolge im Contao Manager eingehalten?

> 1. Alle Pakete zum aktualisieren auswählen
> 2. contao-bootstrap/bundle installieren
> 3. Änderungen anwenden

**Comment by chriza** [comment]
Hallo,
ich komme mit dem Wording nicht klar.

1. Alle Pakete zum aktualisieren auswählen
2. contao-bootstrap/bundle installieren

Wie soll ich bei einer Erstinstallation von conta-bootstrap in einer neuen Contao 4.8.5 Installation die bootstrap Pakete zum aktualisieren auswählen? Ich kann sie bei einer Neuinstallation doch nur hinzufügen.

**Comment by dmolineus** [comment]
> Wie soll ich bei einer Erstinstallation von conta-bootstrap in einer neuen Contao 4.8.5 Installation die bootstrap Pakete zum aktualisieren auswählen

Nicht die Bootstrap-Pakete, sondern alle bereits installierten Pakete (also in der Regel nur Contao).

1. Contao-Manager aufrufen
2. Login
3. Contao-Manager starten
4. Auf Menüpunkt Pakete klicken
5. Pakete aktualisieren klicken
6. NICHT Änderungen anwenden klicken
7. Auf Menüpunkt Entdecken klicken
8. `contao-bootstrap/bundle` suchen
9. Bei `contao-bootstrap/bundle` auf hinzufügen klicken
10. Auf Menüpunkt Pakete klicken
11. Auf Änderungen anwenden klicken

Ist eine Limitierung/Feature vom Contao-Manager, weshalb dieser Weg notwendig ist.

**Comment by chriza** [comment]
Vielen lieben Dank für die Hilfestellung. Werde in Zukunft nach dieser Anleitung vorgehen.
Ich wünsche Ihnen ein schhönes Vorweihnachtswochenende.
